- name: ! "balala\xEFka"
  alcoholic: true
  ingredient:
  - name: cointreau
    quantity: 20
    alcohol: 40
    sugar: 0
    price: 32.6
  - name: ice_cube
    quantity: 54
    alcohol: 0
    sugar: 0
    price: 0.1
  - name: lime
    quantity: 40
    alcohol: 0
    sugar: 0
    price: 3.5
  - name: vodka
    quantity: 40
    alcohol: 40
    sugar: 0
    price: 20
- name: caipirinha
  alcoholic: true
  ingredient:
  - name: cachaca
    quantity: 60
    alcohol: 45
    sugar: 0
    price: 25
  - name: lime
    quantity: 10
    alcohol: 0
    sugar: 0.2
    price: 3.5
  - name: sugar
    quantity: 15
    alcohol: 0
    sugar: 15
    price: 1
- name: coquito
  alcoholic: true
  ingredient:
  - name: cinnamon_stick
    quantity: 80
    alcohol: 0
    sugar: 1.8
    price: 30
  - name: cinnamon_powder
    quantity: 8
    alcohol: 0
    sugar: 0.18
    price: 7
  - name: coconut_cream
    quantity: 200
    alcohol: 0
    sugar: 6.6
    price: 5
  - name: egg_yolk
    quantity: 20
    alcohol: 0
    sugar: 0.12
    price: 7
  - name: nutmeg
    quantity: 8
    alcohol: 0
    sugar: 2.2
    price: 75
  - name: sweetened_condensed_milk
    quantity: 180
    alcohol: 0
    sugar: 99
    price: 7
  - name: vanilla_pod
    quantity: 3.5
    alcohol: 0
    sugar: 0.45
    price: 300
  - name: white_rum
    quantity: 100
    alcohol: 37.5
    sugar: 0
    price: 30
- name: margarita
  alcoholic: true
  ingredient:
  - name: lime
    quantity: 20
    alcohol: 0
    sugar: 0.4
    price: 3.5
  - name: tequila
    quantity: 40
    alcohol: 35
    sugar: 0
    price: 30
  - name: triple_sec
    quantity: 20
    alcohol: 30
    sugar: 0
    price: 21
- name: mojito
  alcoholic: true
  ingredient:
  - name: lime_juice
    quantity: 10
    alcohol: 0
    sugar: 0.25
    price: 3.5
  - name: sparkling_water
    quantity: 300
    alcohol: 0
    sugar: 0
    price: 0.5
  - name: sugarcane_syrup
    quantity: 40
    alcohol: 0
    sugar: 85
    price: 5
  - name: white_rum
    quantity: 40
    alcohol: 37.5
    sugar: 0
    price: 30
- name: pina_colada
  alcoholic: true
  ingredient:
  - name: coconut_milk
    quantity: 40
    alcohol: 0
    sugar: 19
    price: 4.5
  - name: pineapple_juice
    quantity: 60
    alcohol: 0
    sugar: 110
    price: 3
  - name: white_rum
    quantity: 60
    alcohol: 56.25
    sugar: 0
    price: 10
- name: punch
  alcoholic: true
  ingredient:
  - name: grapefruit_juice
    quantity: 100
    alcohol: 0
    sugar: 14
    price: 32
  - name: orange_juice
    quantity: 100
    alcohol: 0
    sugar: 8
    price: 2
  - name: pineapple_juice
    quantity: 100
    alcohol: 0
    sugar: 1.4
    price: 3
  - name: sugarcane_syrup
    quantity: 50
    alcohol: 0
    sugar: 42.5
    price: 5
  - name: white_rum
    quantity: 100
    alcohol: 56.25
    sugar: 0
    price: 10
- name: slushie
  alcoholic: true
  ingredient:
  - name: melon_juice
    quantity: 125
    alcohol: 0
    sugar: 17.5
    price: 3
  - name: pink_wine
    quantity: 250
    alcohol: 12
    sugar: 0
    price: 11
- name: spritz
  alcoholic: true
  ingredient:
  - name: campari
    quantity: 40
    alcohol: 28.5
    sugar: 0
    price: 35
  - name: pineapple_juice
    quantity: 40
    alcohol: 0
    sugar: 5.6
    price: 3
  - name: white_wine
    quantity: 60
    alcohol: 12
    sugar: 0
    price: 10
- name: banarama
  alcoholic: false
  ingredient:
  - name: apricot_juice
    quantity: 120
    alcohol: 0
    sugar: 10.8
    price: 3
  - name: banana_juice
    quantity: 80
    alcohol: 0
    sugar: 17.6
    price: 6
  - name: coconut_milk
    quantity: 40
    alcohol: 0
    sugar: 1.32
    price: 4.5
- name: bora_bora
  alcoholic: false
  ingredient:
  - name: pineapple_juice
    quantity: 100
    alcohol: 0
    sugar: 12
    price: 3
  - name: lime_juice
    quantity: 10
    alcohol: 0
    sugar: 0.25
    price: 3.5
  - name: passion_fruit_juice
    quantity: 60
    alcohol: 0
    sugar: 7.2
    price: 3
  - name: pomegrenate_syrup
    quantity: 20
    alcohol: 0
    sugar: 6
    price: 7
- name: capitole
  alcoholic: false
  ingredient:
  - name: citrus_soda
    quantity: 50
    alcohol: 0
    sugar: 2.85
    price: 4.5
  - name: mint_syrup
    quantity: 5
    alcohol: 0
    sugar: 3.25
    price: 2
  - name: orange_juice
    quantity: 100
    alcohol: 0
    sugar: 8
    price: 2
- name: incorruptible
  alcoholic: false
  ingredient:
  - name: grapefruit_juice
    quantity: 40
    alcohol: 0
    sugar: 5.6
    price: 2
  - name: lime_juice
    quantity: 100
    alcohol: 0
    sugar: 2.5
    price: 3.5
  - name: orange_juice
    quantity: 20
    alcohol: 0
    sugar: 1.6
    price: 2
- name: mocktail
  alcoholic: false
  ingredient:
  - name: cinnamon_syrup
    quantity: 10
    alcohol: 0
    sugar: 5
    price: 10
  - name: citrus_soda
    quantity: 85
    alcohol: 0
    sugar: 4.8
    price: 4.5
  - name: orange_juice
    quantity: 40
    alcohol: 0
    sugar: 3.2
    price: 2
  - name: strawberry_syrup
    quantity: 20
    alcohol: 0
    sugar: 16.8
    price: 4.5
- name: nojito
  alcoholic: false
  ingredient:
  - name: lime_juice
    quantity: 10
    alcohol: 0
    sugar: 0.25
    price: 3.5
  - name: sparkling_water
    quantity: 150
    alcohol: 0
    sugar: 0
    price: 0.5
  - name: sugarcane_syrup
    quantity: 30
    alcohol: 0
    sugar: 25.5
    price: 5
- name: pina_colada_na
  alcoholic: false
  ingredient:
  - name: coconut_milk
    quantity: 50
    alcohol: 0
    sugar: 1.6
    price: 4.5
  - name: pina_colada_syrup
    quantity: 15
    alcohol: 0
    sugar: 12.15
    price: 11.5
  - name: pineapple_juice
    quantity: 100
    alcohol: 0
    sugar: 14
    price: 3
- name: punch_na
  alcoholic: false
  ingredient:
  - name: grapefruit_juice
    quantity: 190
    alcohol: 0
    sugar: 26.6
    price: 2
  - name: orange_juice
    quantity: 190
    alcohol: 0
    sugar: 15.2
    price: 2
  - name: pineapple_juice
    quantity: 190
    alcohol: 0
    sugar: 26.6
    price: 3
  - name: sugarcane_syrup
    quantity: 50
    alcohol: 0
    sugar: 42.5
    price: 5
- name: rio
  alcoholic: false
  ingredient:
  - name: lime_juice
    quantity: 125
    alcohol: 0
    sugar: 3.125
    price: 3.5
  - name: orange_juice
    quantity: 125
    alcohol: 0
    sugar: 2.5
    price: 2
  - name: pomegrenate_syrup
    quantity: 15
    alcohol: 0
    sugar: 7.05
    price: 3
- name: summer_lemonade
  alcoholic: false
  ingredient:
  - name: lime_juice
    quantity: 40
    alcohol: 0
    sugar: 1
    price: 3.5
  - name: melon_juice
    quantity: 15
    alcohol: 0
    sugar: 2.1
    price: 3
  - name: sugar
    quantity: 15
    alcohol: 0
    sugar: 15
    price: 1
  - name: water
    quantity: 25
    alcohol: 0
    sugar: 0
    price: 0.2
  - name: watermelon_juice
    quantity: 150
    alcohol: 0
    sugar: 1.01
    price: 7.8
